### ISSUE TITLE
ssrmu可以增多服务器ip配置么

### ISSUE THREAD

**Issue by ghost** [fanvinga/dockerfiles#10]
ssrmu可以增多服务器ip配置么
用ssr打游戏同ip开多了就封号
再买一台VPS的成本要远大于加IP地址

**Comment by fanvinga** [comment]
使用--network=host参数启动时.网络中所有可达的IP都会拥有访问容器端口的规则.无需对容器进行额外配置.确认ip绑定正确即可.
