### ISSUE TITLE
Add goflyway

### ISSUE THREAD

**Issue by lovefoolu** [fanvinga/dockerfiles#4]
项目地址：https://github.com/coyove/goflyway
翻遍了你的VINGA'S Blog、Docker Hub，只有brook，能添加一下goflyway吗？

**Comment by fanvinga** [comment]
很抱歉现在才看到你的issue.因为最近事情比较多😂😂 goflyway 我个人了解是好像有不少现成的docker image.或许你可以考虑一下使用？
我没做只是单纯觉得用处不大😂😂
