### ISSUE TITLE
docker-ssrmu: prefer ipv4 over ipv6

### ISSUE THREAD

**Issue by sjtuross** [fanvinga/dockerfiles#5]
在docker环境里，一直是ipv6优先

docker exec -it xxxxxxxxx /bin/bash 之后，可以通过curl ifconfig.co确认返回的是ipv6，通过curl -4 ifconfig.co返回的就是ipv4

我并不想禁用ipv6，请问有什么办法在容器中的Alpine Linux里设置ipv4优先？

**Comment by fanvinga** [comment]
事实上这个问题跟容器中的alpine无关.而跟docker0这张docker daemon生成的虚拟网卡有关系.如果docker0这张vNIC得到并且绑定了宿主机上IPv6的地址.并且配置的路由默认是使用IPv6的.那么在内部容器对外访问的时候就会优先使用IPv6的地址.
* 如果你想让容器访问的网络是纯ipv4的话.你可能需要在docker daemon的启动参数中加入`ipv6=false`或者修改`/etc/docker/daemon.json`加入以上参数.或者使用特定的sysctl参数禁用IPv6访问.
* 如果要设置ipv4优先.可以考虑修改宿主机中的相应路由.使得默认路由通过ipv4链路.

**Comment by fanvinga** [comment]
可以参考这个[issue](https://github.com/moby/moby/issues/2174)中的相关讨论
