### ISSUE TITLE
抱歉fork修改东西，不小心推送到主项目了

### ISSUE THREAD

**Issue by neighbor007** [fanvinga/dockerfiles#8]
抱歉，我fork了一下，加几个自己要用的字段，不小心推送到了你的主项目，很抱歉很抱歉。

**Comment by fanvinga** [comment]
我以为加功能呢直接merge了🙃

**Comment by neighbor007** [comment]
抱歉抱歉，你修改回去吧，这个单端口偏移对于深港这样的线路，统计不到用户消耗流量，还有其它地方要改。
